spring:
  application:
    name: 'Sistema de gestión operativa integral - Grupo las vegas'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_mqoX49I0Z/.well-known/jwks.json
aws:
  region: ${COGNITO_REGION}
  cognito:
    userPoolId: ${COGNITO_USER_POOL_ID:us-east-1_mqoX49I0Z}
    clientId: ${COGNITO_CLIENT_ID}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
